# name: Docker Build and Push

# on:
#   workflow_dispatch:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1

#       - name: Login to Docker Hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Build and Push Docker Image
#         run: |
#           docker buildx build --tag harsshh/guest-book:${{ github.sha }} -f guestbook-go/Dockerfile .
#           docker buildx build --tag harsshh/guestbook-go:latest -f guestbook-go/Dockerfile .
#           docker push harsshh/guestbook-go:${{ github.sha }}
#           docker push harsshh/guestbook-go:latest

name: Build and push Docker image
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v2
        with:
          path: .
          file: Dockerfile
